# Generated by Django 4.2.2 on 2025-09-22 16:35

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usefulthings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wont",
            name="period",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Число повторений в неделю"
            ),
        ),
        migrations.AlterField(
            model_name="wont",
            name="time_to_action",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                verbose_name="Время на выполнение",
            ),
        ),
    ]
